### ISSUE TITLE
Allow to drop in the root collection

### ISSUE THREAD

**Issue by lionelB** [tchatel/angular-treeRepeat#8]
Actually, there is no way to drag an element in the root collection.
Once an element is a children of another node, it's impossible to move this node at the root level.

**Comment by couzic** [comment]
If I remember well, I handled this problem by wrapping the root level inside another array. In my case I had only a single root node, the solution looked like this in my template

`<li frang-tree-repeat="node in [myRootNode]">`

Hope it helps !

**Comment by lionelB** [comment]
Nice thanks you!
