### ISSUE TITLE
Does frang-tree-repeat get re-evaluated?

### ISSUE THREAD

**Issue by tpederson** [tchatel/angular-treeRepeat#9]
If I change the data that I use in the frang-tree-repeat="", the tree is not updated. Perhaps I am doing something wrong. If not, is there a way to force the tree to re-evaluate?

**Comment by couzic** [comment]
I think you are doing something wrong. Do you have a piece of code to show ?

**Comment by tpederson** [comment]
You are right Mikael, I am sorry. Should I delete the issue?

**Comment by couzic** [comment]
Well, if you think this is a non-issue, then I'd say yes.

Cheers !

## 

Mikael Couzic

84, rue Vergniaud
75013 Paris
09 54 90 02 55
06 51 17 97 83

2014-07-31 21:38 GMT+02:00 tpederson notifications@github.com:
